// <auto-generated />
namespace AutoDealer.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ExistSubModelEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExistSubModelEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201912301522502_ExistSubModel-Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
