// <auto-generated />
namespace AutoDealer.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changeRelationwithinCarandSubModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeRelationwithinCarandSubModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202001181321357_change Relation within Car and SubModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
