// <auto-generated />
namespace AutoDealer.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddOptionEntityandoption_categoryentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOptionEntityandoption_categoryentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040801133_Add Option Entity and option_category entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
